### ISSUE TITLE
Only Works In repl.it, not VSCode | Randomizer Issue

### ISSUE THREAD

**Issue by Justiniscoding** [RedYetiDev/blooket.js#5] opened 2021-02-23 01:02 UTC
i was testing this in vscode and i got an error saying it is an invalid pin. i used the exact same script in repl.it and it worked perfectly. why did i get the error.

**Comment by RedYetiDev** [comment] 2021-02-23 02:29
Can you please give more information. The issue might be that Visual Studio Code does not allow access to the network. Try running  the following snippet and see what is logged
```js
const ws = require("ws");
var socket = new ws("wss://echo.websocket.org")
socket.on("message", function(d) {
console.log(d)
})
socket.on("open", function() {
socket.send("Test Message")
})
```
PS: If this message looks weird, it is because I am sending it as an email.

From, 
RedYetiDev

On February 22, 2021, at 8:02 PM, Justiniscoding <notifications@github.com> wrote:

i was testing this in vscode and i got an error saying it is an invalid pin. i used the exact same script in repl.it and it worked perfectly. why did i get the error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/RedYetiDev/blooket.js/issues/5">https://github.com/RedYetiDev/blooket.js/issues/5</a>", "url": "<a href="https://github.com/RedYetiDev/blooket.js/issues/5">https://github.com/RedYetiDev/blooket.js/issues/5</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by RedYetiDev** [comment] 2021-02-23 11:13
Can you please give more information. The issue might be that Visual Studio Code does not allow access to the network. Try running  the following snippet and see what is logged

```js
const ws = require("ws");
var socket = new ws("wss://echo.websocket.org")
socket.on("message", function(d) {
console.log(d)
})
socket.on("open", function() {
socket.send("Test Message")
})
```

**Comment by RedYetiDev** [comment] 2021-02-23 11:14
I fixed the comment. (Sorry for accidentally closing the issue)

**Comment by RedYetiDev** [comment] 2021-02-23 13:58
Any luck?

**Comment by RedYetiDev** [comment] 2021-02-23 14:25
The issue might be a in the Blooket.JS Script. in `modules/socket.js`, around `line 83`
```js
var socket = new WebSocket(wss:// ... )
```
Should be
```js
var socket = new WebSocket(sockets[4])
```
This issue will be fixed in version 1.2.0

**Comment by Justiniscoding** [comment] 2021-02-23 14:30
ok, any plans on when it will be out?

**Comment by RedYetiDev** [comment] 2021-02-23 14:31
Later today.

**Comment by Justiniscoding** [comment] 2021-02-23 14:31
ok

**Comment by RedYetiDev** [comment] 2021-02-23 14:31
I just need to finish up allowing support for the new `Tower Defense` Game Mode

**Comment by Justiniscoding** [comment] 2021-02-23 14:32
yes, that will be hard. i tried it and it is very intuitive. not the best for bots

**Comment by RedYetiDev** [comment] 2021-02-23 14:34
Well, The bot is not going to "playing" the game, well, at least not in version 1.2, but it will be giving 1 point to the player each time a question is answered, kind of skipping the whole "defense" concept. This might be changed, but for now, this is what works

**Comment by Justiniscoding** [comment] 2021-02-23 14:37
@RedYetiDev line 100 in blooket.js is wrong. It was like that for me because i used .replace(). you have to change it so that each underscore becomes a space. for example: Snowy_Owl should be Snowy Owl

**Comment by RedYetiDev** [comment] 2021-02-23 14:42
Will fix, I converted it to a list incorrectly.

**Comment by RedYetiDev** [comment] 2021-02-23 14:47
Patched in next update.

**Comment by Justiniscoding** [comment] 2021-02-23 14:51
why did you write randomized issue?

**Comment by Justiniscoding** [comment] 2021-02-23 15:51
@RedYetiDev Sorry for the delay, i ran it and i got Test Message! in the console

**Comment by Justiniscoding** [comment] 2021-02-23 15:56
@RedYetiDev i tested it now it works!

**Comment by RedYetiDev** [comment] 2021-02-23 16:01
Odd, The original issue might be caused by the "socket.js" issue

**Comment by RedYetiDev** [comment] 2021-02-23 16:03
PS: Sorry that it originally took me 10 hours to give my first response on this issue, I was working on my [website](https://redyetidev.github.io) and [Jekyll Theme](https://github.com/redyetidev/Portfolio-Theme). For comments regarding to them, make issues on their repos.

**Comment by Justiniscoding** [comment] 2021-02-23 17:34
@RedYetiDev  update to the randomized issue: i used ```game.randomblook()``` and got unreturned object promise as my blook

**Comment by RedYetiDev** [comment] 2021-02-23 17:40
Please resubmit this as a bug report

**Closed** 2021-02-23 17:42 UTC
Labels: Patched In next update, bug
